[package]
name = "linear_algebra_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
clap = "4.4.0"
rusymbols = "0.1.0"
colored = "2.0.0"
regex  = "1"